name: swagdeliverystars
services:
  backend:
    build: .
    container_name: swagdeliverystars-backend
    networks:
      - server-side
      - client-side
    ports:
      - 5000:5000

networks:
  client-side: {}
  server-side: {}

